### PR TITLE
Michaels Alphabetical Playlist

### PR DESCRIPTION
**Pull request by Mike01999**
I put the list in alphabetical order by the songs that the people that made them.

### CODE REVIEW

**Comment by lee2sman** [comment]
Hi Michael, thanks. Can you make a sub-folder called personal-playlists and then place your playlists in there? And make sure the filename doesn't have periods or spaces.

**Comment by Mike01999** [comment]
Did you want me to create a new file and put my playlists in there. I'm not sure how to create a new folder because I don't want to accidently delete anything.

**Comment by lee2sman** [comment]
It's okay to make mistakes and try stuff! The advantage of this overly difficult system is that everything is saved in memory and we can always jump back in time! 

My suggestion is to try making a new folder, perhaps called ```student_playlists``` or ```personal_playlists``` and then move your playlist in there. Then submit a pull request.

**Comment by Mike01999** [comment]
I just did the personal playlist. I forgot to ask but when you wanted me to put my playlist in a folder did you want me to add my alphabetical and normal playlist or just the alphabetical because both of them are the same in different order

**Pull request closed without merging**
