### PR TITLE
Michaels-list.md

### PR DESCRIPTION
**Pull request by Mike01999**
This is music that I like. I hope that I did it right.

### CODE REVIEW

**Comment by lee2sman** [comment]
Michael, you made your own playlist? great!

can you make a minor change for me? To get the text to appear correctly on GitHub, can you rename the file with the correct ending? the filename should end with ```.md``` which stands for [markdown](https://en.wikipedia.org/wiki/Markdown). I believe you can click edit and rename and then commit it.

**Comment by lee2sman** [comment]
maybe change the file name to ```michaels-list.md``` or something like that so people know what it is?

**Comment by Mike01999** [comment]
Sure I just edited the title does that work.

**Comment by lee2sman** [comment]
the file still has the old title. make that change, hit commit and i can then review and merge. thanks

**Comment by Mike01999** [comment]
Got it this time I'm pretty sure I changed the filename

**Comment by Mike01999** [comment]
I just renamed it

**Review by lee2sman — APPROVED** [review]

**Pull request merged**
